version: "3.8"

volumes:
  mongo-data:
    driver: local

services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tasty-task
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./seed-data:/docker-entrypoint-initdb.d/seed-data:ro